export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_INPUT: 'INVALID_INPUT',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  INVALID_BOOK_STATE: 'INVALID_BOOK_STATE',
  CHECKOUT_EMPTY: 'CHECKOUT_EMPTY',
  BANNED: 'BANNED',
  WX_LOGIN_FAILED: 'WX_LOGIN_FAILED',
  FEE_PROPOSAL_NOT_FOUND: 'FEE_PROPOSAL_NOT_FOUND',
  DISPUTE_NOT_FOUND: 'DISPUTE_NOT_FOUND',
  ANNOUNCEMENT_NOT_FOUND: 'ANNOUNCEMENT_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
  };
}
